spring:
  application:
    name: microservice-dept
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



mybatis:
  type-aliases-package: com.wyg.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
#      defaultZone: http://eureka7001:7001/eureka
  instance:
    instance-id: microservice-demo-dept8001
    prefer-ip-address: true

info:
  app.name: wyg.microservice
  company.name: www.wyg.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$






