server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 40000




